### ISSUE TITLE
Unable to run wrapper with JDK 7

### ISSUE THREAD

**Issue by luisespinal** [takari/maven-wrapper#162]
Hello, I'm trying to run/add the wrapper to a maven project that requires JDK 7 and Maven 3.0.5.

I get the following error when I try **mvn -N io.takari:maven:0.7.7:wrapper -Dmaven=3.0.5** or just **mvn -N io.takari:maven:0.7.7:wrapper** 

Any ideas?

```
Dec 10, 2019 2:10:41 PM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: io.takari.maven.plugins.WrapperMojo
java.lang.TypeNotPresentException: Type io.takari.maven.plugins.WrapperMojo not present
        at org.sonatype.guice.bean.reflect.URLClassSpace.loadClass(URLClassSpace.java:109)
        at org.sonatype.guice.bean.reflect.NamedClass.load(NamedClass.java:45)
        at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
       ... stuff omitted ...
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.UnsupportedClassVersionError: io/takari/maven/plugins/WrapperMojo : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)

```

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.
