### ISSUE TITLE
error: input is not in gz format

### ISSUE THREAD

**Issue by jangalinski** [takari/maven-wrapper#54]
I do `mvn -N io.takari:maven:wrapper -Dmaven=3.3.9` (windows7, gitbash, maven 3.3.9)

and get:

```
Failed to execute goal io.takari:maven:0.4.1:wrapper (default-cli) on project bpa-platform: 
Error installing the maven-wrapper archive. Cannot determine the type of archive ...\.m2\repository\io\takari
\maven-wrapper\0.2.1\maven-wrapper-0.2.1.tar.gz. Input is not in the .gz format -> [Help 1]
```

ideas?

**Comment by mosabua** [comment]
I cant reproduce this problem. Can you try with 0.4.2?

**Comment by larsgrefer** [comment]
I have the same issue:

```java
[ERROR] Failed to execute goal io.takari:maven:0.4.3:wrapper (default-cli) on project adminportal-reactor: Error installing the maven-wrapper archive. Cannot determine the type of archive /home/lgrefer/.m2/repository/io/takari/maven-wrapper/0.2.3/maven-wrapper-0.2.3.tar.gz. Input is not in the .gz format -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.takari:maven:0.4.3:wrapper (default-cli) on project adminportal-reactor: Error installing the maven-wrapper archive.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error installing the maven-wrapper archive.
        at io.takari.maven.plugins.WrapperMojo.execute(WrapperMojo.java:67)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.RuntimeException: Cannot determine the type of archive /home/lgrefer/.m2/repository/io/takari/maven-wrapper/0.2.3/maven-wrapper-0.2.3.tar.gz.
        at io.tesla.proviso.archive.tar.TarGzArchiveSource.<init>(TarGzArchiveSource.java:29)
        at io.tesla.proviso.archive.tar.TarGzArchiveHandler.getArchiveSource(TarGzArchiveHandler.java:44)
        at io.tesla.proviso.archive.UnArchiver.unarchive(UnArchiver.java:54)
        at io.tesla.proviso.archive.UnArchiver.unarchive(UnArchiver.java:44)
        at io.takari.maven.plugins.WrapperMojo.execute(WrapperMojo.java:60)
        ... 22 more
Caused by: java.io.IOException: Input is not in the .gz format
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.init(GzipCompressorInputStream.java:164)
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:137)
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:102)
        at io.tesla.proviso.archive.tar.TarGzArchiveHandler.getInputStream(TarGzArchiveHandler.java:34)
        at io.tesla.proviso.archive.tar.TarGzArchiveSource.<init>(TarGzArchiveSource.java:27)
        ... 26 more
```

The command I've executed was:

```sh
mvn -N io.takari:maven:wrapper -Djava.net.useSystemProxies=true -e
```

This is my system:
```
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "4.10.0-33-generic", arch: "amd64", family: "unix"
```

**Possible hint:** The downloaded file (`~/.m2/repository/io/takari/maven-wrapper/0.2.3/maven-wrapper-0.2.3.tar.gz`) is empty (0 Bytes)

**Comment by mosabua** [comment]
Are you sure that your system proxy is not breaking the download? It works just fine so at this stage I am assuming that your network setup is at fault.

**Comment by jangalinski** [comment]
I guess the proxy was blocking in my case ...
