### ISSUE TITLE
Allowing specify JDK requirements in the properties 

### ISSUE THREAD

**Issue by jvanzyl** [takari/maven-wrapper#59]
If you fire up the Maven Wrapper with an older JDK you get the dreaded `java.lang.UnsupportedClassVersionError` error. We should detect the JDK and display a usable error message with instructions for correcting the problem.

**Comment by mosabua** [comment]
This would have to be done in the command line scripts calling a Java version or so .. just fyi for anyone wanting to send a PR for this for the next release.

**Comment by mosabua** [comment]
Just our of curiosity .. what JDK versions does this problem even show up? I think everything in maven-wrapper is java 5 ..

**Comment by luisespinal** [comment]
> Just our of curiosity .. what JDK versions does this problem even show up? I think everything in maven-wrapper is java 5 ..

I have that problem under JDK 7 when trying run `mvn -N io.takari:maven:0.7.7:wrapper -Dmaven=3.0.5` (or simply mvn -N io.takari:maven:0.7.7:wrapper):


```
Dec 10, 2019 2:10:41 PM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: io.takari.maven.plugins.WrapperMojo
java.lang.TypeNotPresentException: Type io.takari.maven.plugins.WrapperMojo not present
        at org.sonatype.guice.bean.reflect.URLClassSpace.loadClass(URLClassSpace.java:109)
        at org.sonatype.guice.bean.reflect.NamedClass.load(NamedClass.java:45)
        at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
       ... stuff omitted ...
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.UnsupportedClassVersionError: io/takari/maven/plugins/WrapperMojo : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
```

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.
