### ISSUE TITLE
Misleading error message in case maven zip file is corrupt

### ISSUE THREAD

**Issue by arminwasicek** [takari/maven-wrapper#91]
Given that the maven library in, e.g.,  ```~/.m2/wrapper/dists/apache-maven-3.5.2-bin/28qa8v9e2mq69covern8vmdkj0/apache-maven-3.5.2-bin.zip``` is corrupt, `java.util.zip.ZipFile` stops with this misleading error message:

```Exception in thread "main" java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:225)
    at java.util.zip.ZipFile.<init>(ZipFile.java:155)
    at java.util.zip.ZipFile.<init>(ZipFile.java:169)
    at org.apache.maven.wrapper.Installer.unzip(Installer.java:161)
    at org.apache.maven.wrapper.Installer.createDist(Installer.java:78)
    at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
    at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)```

It suggests that the error is on the level of the filesystem, however, the contents of the file is not a correct zip byte stream. A better way of responding would be to indicate that the zip file could not be expanded like "error in expanding zip file".

**Comment by mosabua** [comment]
How do you even get to that problem? I cant reproduce it in normal operation and usage.
